### PR TITLE
Stages are sorted according to their index

### LINKED ISSUE #248: [Bug]: Stages are not sorted on Papers page
### Is there an existing issue for this?

- [x] I have searched the existing issues

### To which use case does your bug report relate?

#31

### What happened?

When opening the "Papers" page in a project, it can happen that the stages are not sorted, as can be seen here

Image

When all of the papers for the project are requested they must not be sorted by their stage, but the method `organizePapersByStage` in the `routes/project/[projectId]/papers/page.ts` file assign the papers to their stages without sorting the stages or the papers by their stage. So it can happen that the first paper is in stage 1 and the second paper is in stage 0 and then stage 1 is added to the list of stages before stage 0.

### Steps to reproduce

1. Go to the "Papers" view for different projects
2. Check the stages list

### What did you expect?

The stages to be sorted from stage _0_ to stage _n_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Slartibartfass2**
Closes #248 

## What I have made

- See issue

## Checklist

Either tick or cross out the items that do not apply (using \~\~example text\~\~) and give a reason why the item does not apply.

- [x] I have updated the documentation accordingly and commented my code
- ~[ ] I have added tests that prove my fix is effective or that my feature works~ (only e2e tests would've made sense, but they do not exist yet)
- [x] (for reviewer) I have checked the implementation against the requirements

### CODE REVIEW

File: src/routes/project/[projectId]/papers/+page.ts [hunk 1]
```diff
@@ -70,5 +71,6 @@ function organizePapersByStage(papers: Project_Paper[]): Stage[] {
 
         stage.papers.push(paper);
     }
-    return stages;
+    stages.forEach((stage) => stage.papers.sort((a, b) => comparePaperId(b.id, a.id)));
```
Comment (Merseleo) [inline src/routes/project/[projectId]/papers/+page.ts:75]: I appreciate that you sort the papers in the stage. But as there exist an issue for that (see #39), I would appreciate this line even more, you maybe move the sorting of the papers from the load function to the `StageEntry` component and add a hint to this issue. Would that be ok or do you want to keep the sorting at this point the `StageEntry` component should override the order if necessary?

**Review by Merseleo — COMMENTED** [review]
Only a little question, but I think the bug has been fixed.

File: src/routes/project/[projectId]/papers/+page.ts (hunk 1 above)
Comment (Slartibartfass2) [reply src/routes/project/[projectId]/papers/+page.ts:75]: I think this is fine for the initial order, other sorting should be made in `StageEntry`. If that's okay for you too.

Comment (Merseleo) [reply src/routes/project/[projectId]/papers/+page.ts:75]: It is, especially as the sorting will be integrated soon.

**Review by Merseleo — APPROVED** [review]
All questions answered ...
