### PR TITLE
fix: correctly show loading spinner for navigation buttons

### LINKED ISSUE #462: [Bug]: Flickering review buttons
### Is there an existing issue for this?

- [x] I have searched the existing issues

### To which use case does your bug report relate?

#52

### What happened?

If one of the decision buttons is clicked, then the buttons disappear until the data for the next paper is loaded. At the moment the buttonsseem to flicker because of the short disappearance.

### Steps to reproduce

1. Go to the paper view of a project paper
2. Click on one of the review decision buttons

### What did you expect?

The expected behaviour would be, to show the loading spinner as long as the current paper is shown and the disabled buttons as long as the paper data is not fully loaded on the next papers page. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by domienderle**
Closes 

## What I have made

- I removed the `await`-statement in the `PaperView.svelte`, which causes the flickering of the review decision buttons
- I have added a global state for the buttons in the project paper view, which handles the loading of the ressources for all five buttons at once. 
- Additionally, I fixed a couple of bugs regardings the loading spinner of the paper navigation buttons and the review decision buttons.

## Checklist

Either tick or cross out the items that do not apply (using \~\~example text\~\~) and give a reason why the item does not apply.

- [x] I have updated the documentation accordingly and commented my code
- [x] I have added tests that prove my fix is effective or that my feature works
  - [x] unit tests
  - [x] integration tests
  - [x] end-to-end tests
- [x] (for reviewer) I have checked the implementation against the requirements

### CODE REVIEW

File: src/lib/global-state/project-paper-loading-state.svelte.ts
Comment (mowi12) [inline src/lib/global-state/project-paper-loading-state.svelte.ts:1]: This looks perfect, but please a comment, explaining what this stores exactly. Similar to all the other global states.

File: src/lib/components/composites/paper-components/paper-view/PaperNavigationButton.svelte [hunk 1]
```diff
@@ -23,19 +23,23 @@
...
-        loading = showLoadingSpinner.value;
-    });
+    let buttonStillLoading: boolean = $state(true);
+
+    const isDisabled: boolean = $derived(
+        projectPaperLoading.isLoading ||
+            (direction === "right" ? buttonRightDisabled : buttonLeftDisabled) ||
+            buttonStillLoading,
+    );
+    let isLoading: boolean = $derived(projectPaperLoading.isLoading || buttonStillLoading);
```
Comment (mowi12) [inline src/lib/components/composites/paper-components/paper-view/PaperNavigationButton.svelte]: What about:

```suggestion
    const isLoading: boolean = $derived(projectPaperLoading.isLoading || buttonStillLoading);
    const isDisabled: boolean = $derived(
        isLoading || (direction === "right" ? buttonRightDisabled : buttonLeftDisabled),
    );
```

1. You can use `const` for `isLoading` since it's never reassigned.
2. You can reuse the `isLoading` in the evaluation of `isDisabled`, since it uses the same variables to compute the `isDisabled` state.

File: src/lib/components/composites/paper-components/paper-view/PaperDecisionButton.svelte [hunk 2]
```diff
@@ -22,40 +23,35 @@
...
-    $effect(() => {
+    /*  $effect(() => {
         // Update `isSubmittingReview` every time `showLoadingSpinner` is updated
         // `isSubmittingReview` is used as a state in the `PaperView` component to disable all decision buttons while
         // the API call is made. However we need a different sate for displaying the loading state of the single
         // decision button. Otherwise, all would have a spinner and label with "Submitting Review".
         isSubmittingReview.value = showLoadingSpinner.value;
-        loading = showLoadingSpinner.value;
-    });
+    });*/
```
Comment (mowi12) [inline src/lib/components/composites/paper-components/paper-view/PaperDecisionButton.svelte]: If this is not used any more, why not remove it completely?

File: src/lib/components/composites/paper-components/paper-view/PaperDecisionButton.svelte [hunk 3]
```diff
@@ -209,8 +212,11 @@ Usage:
         paperDecisionButtonVariants({ variant: variant }),
     )}
     data-testid={`decision-button-${variant}`}
-    disabled={isSubmittingReview.value || wasAlreadyReviewed || showLoadingSpinner.value || loading}
-    loading={showLoadingSpinner.value}
+    disabled={isSubmittingReview.value ||
+        wasAlreadyReviewed ||
+        showLoadingSpinner.value ||
+        projectPaperLoading.isLoading}
+    loading={projectPaperLoading.isLoading || isSubmittingReview.value}
```
Comment (mowi12) [inline src/lib/components/composites/paper-components/paper-view/PaperDecisionButton.svelte]: This is pretty clunky. What about creating a `isLoading` and `isDisabled` variable at the top, similar to the other files, and only using these variables here?

**Review by mowi12 — CHANGES_REQUESTED** [review]
The logic works and for me, everything looks fine in the UI.
There are only some refactorings you need to look at.

File: src/lib/global-state/project-paper-loading-state.svelte.ts
Comment (domienderle) [reply src/lib/global-state/project-paper-loading-state.svelte.ts:1]: Good catch. I completely missed this after it worked.

File: src/lib/components/composites/paper-components/paper-view/PaperNavigationButton.svelte (hunk 1 above)
Comment (domienderle) [reply src/lib/components/composites/paper-components/paper-view/PaperNavigationButton.svelte]: Good catch. Looks good.

File: src/lib/components/composites/paper-components/paper-view/PaperDecisionButton.svelte (hunk 2 above)
Comment (domienderle) [reply src/lib/components/composites/paper-components/paper-view/PaperDecisionButton.svelte]: I just forgot to remove it.

File: src/lib/components/composites/paper-components/paper-view/PaperDecisionButton.svelte (hunk 3 above)
Comment (domienderle) [reply src/lib/components/composites/paper-components/paper-view/PaperDecisionButton.svelte]: Good idea. Is done.

File: src/lib/components/composites/paper-components/paper-view/PaperDecisionButton.svelte [hunk 4]
```diff
@@ -22,40 +23,35 @@
...
-        // decision button. Otherwise, all would have a spinner and label with "Submitting Review".
-        isSubmittingReview.value = showLoadingSpinner.value;
-        loading = showLoadingSpinner.value;
-    });
+    const isLoading = $derived(projectPaperLoading.isLoading || isSubmittingReview.value);
+    const isDisabled = $derived(
+        isLoading ||
+            wasAlreadyReviewed ||
+            showLoadingSpinner.value ||
+            projectPaperLoading.isLoading,
```
Comment (mowi12) [inline src/lib/components/composites/paper-components/paper-view/PaperDecisionButton.svelte]: I think this is duplicated, since it is also included in `isLoading`

**Review by mowi12 — CHANGES_REQUESTED** [review]
Nicely done!
Only one last thing.

File: src/lib/components/composites/paper-components/paper-view/PaperDecisionButton.svelte (hunk 4 above)
Comment (domienderle) [reply src/lib/components/composites/paper-components/paper-view/PaperDecisionButton.svelte]: Shit, you are right. Thanks.

**Review by mowi12 — APPROVED** [review]
