### PR TITLE
Fix PaperBookmarkButton

### LINKED ISSUE #589: [Bug]: PaperBookmarkButton isn't reloaded when navigating paper
### Is there an existing issue for this?

- [x] I have searched the existing issues

### To which use case does your bug report relate?

#99

### What happened?

When navigating papers, the paper bookmark status isn't correctly loaded.

### Steps to reproduce

Image

See that paper with ID 4 and title "a" is shown as bookmarked but isn't on the reading list.

### What did you expect?

Paper with ID 4 shouldn't be shown as bookmarked.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Slartibartfass2**
Closes #589 

## What I have made

bug-fix

## Checklist

Either tick or cross out the items that do not apply (using \~\~example text\~\~) and give a reason why the item does not apply.

### Author

- [x] I have updated the documentation accordingly and commented my code
- [x] I manually tested the changes
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~

### Reviewer

- [x] I have checked the implementation against the requirements
- [x] I have checked for flaky tests in the CI

### CODE REVIEW

File: src/lib/components/composites/button/PaperBookmarkButton.svelte [hunk 1]
```diff
@@ -6,30 +6,28 @@
     import { resource } from "$lib/resource.svelte";
     import { backendService } from "$lib/grpc-api";
     import { cn } from "$lib/utils/shadcn-helper";
+    import { LoaderCircle } from "lucide-svelte";
 
     interface Props {
-        loadingPaperId: Promise<string>;
+        paperId: string;
```
Comment (Merseleo) [inline src/lib/components/composites/button/PaperBookmarkButton.svelte:12]: You forgot to adapt the comment.

File: src/lib/components/composites/button/PaperBookmarkButton.svelte [hunk 2]
```diff
@@ -6,30 +6,28 @@
...
     const {
-        loadingPaperId,
+        paperId,
         isBookmarkedDefault = false,
         onPaperChangedBookmarkStatus = undefined,
         class: className,
     }: Props = $props();
 
+    console.log("foo");
+
```
Comment (Merseleo) [inline src/lib/components/composites/button/PaperBookmarkButton.svelte]: Please remove this.

File: src/lib/components/composites/button/PaperBookmarkButton.svelte [hunk 3]
```diff
@@ -128,7 +120,9 @@ Usage:
     onmouseleave={onMouseLeave}
 >
     {#snippet trigger()}
-        {#if isHovered}
+        {#if isUpdatingBookmarkStatus}
+            <LoaderCircle class="animate-spin" />
```
Comment (Merseleo) [inline src/lib/components/composites/button/PaperBookmarkButton.svelte:122]: In theory we could also use the new `Spinner` shadcn component, what do you think?

**Review by Merseleo — CHANGES_REQUESTED** [review]
I think only minor things have to be cleaned up

File: src/lib/components/composites/button/PaperBookmarkButton.svelte (hunk 1 above)
Comment (Slartibartfass2) [reply src/lib/components/composites/button/PaperBookmarkButton.svelte:12]: Fixed it.

File: src/lib/components/composites/button/PaperBookmarkButton.svelte (hunk 2 above)
Comment (Slartibartfass2) [reply src/lib/components/composites/button/PaperBookmarkButton.svelte]: Forgot that. I removed it.

File: src/lib/components/composites/button/PaperBookmarkButton.svelte (hunk 3 above)
Comment (Slartibartfass2) [reply src/lib/components/composites/button/PaperBookmarkButton.svelte:122]: There appears to be a problem with this. Also, something changed with the lucide-svelte package. I would do this in another PR.

**Review by Merseleo — APPROVED** [review]
LGTM
