### PR TITLE
Fix inconsistent paddings

### LINKED ISSUE #293: Bug: Inconsistent Paddings Between Main Page and Project Page
There seem to be inconsistent paddings, which lead to the `Open Reviews` header text jumping when directly switching between `/` and `/project/0` pages.

https://github.com/user-attachments/assets/a6751af9-8dc8-4449-9d3f-d7064633b5f9

### PR DESCRIPTION
**Pull request by mowi12**
Closes #293 

## What I have made

Removed vertical and horizontal from different components in order to make them consistent.
Add 'global' horizontal padding to keep all components spacing the same.

## Checklist

- [x] I have updated the documentation accordingly and commented my code
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
  - No source code edited
- [x] (for reviewer) I have checked the implementation against the requirements

### CODE REVIEW

File: src/routes/+page.svelte [hunk 1]
```diff
@@ -16,7 +16,7 @@
     <title>SnowballR</title>
 </svelte:head>
 <SimpleNavigationBar loadingTitle={Promise.resolve("SnowballR")} {user} />
-<main class="mb-10 flex h-full w-full flex-row gap-x-5 overflow-hidden">
+<main class="mb-10 flex h-full w-full flex-row gap-x-5 overflow-hidden px-5">
```
Comment (Merseleo) [inline src/routes/+page.svelte]:
```suggestion
<main class="mb-10 flex h-full w-full flex-row gap-x-15 overflow-hidden px-5">
```
I agree that it is smarter to handle the padding on the homepage and not within the `NamedList` component, however the gap between the two list on the homepage very small

File: src/lib/components/composites/paper-components/paper-view/PaperView.svelte [hunk 2]
```diff
@@ -120,7 +120,7 @@ Usage:
     <!-- TODO: Set `isBookmarkedDefault` as soon as endpoint is available -->
     <PaperBookmarkButton isBookmarkedDefault={false} {loadingPaperId} />
 </div>
-<main class="flex h-full w-full flex-col gap-5 px-2 py-4">
+<main class="flex h-full w-full flex-col gap-5 px-5">
```
Comment (Merseleo) [inline src/lib/components/composites/paper-components/paper-view/PaperView.svelte]:
```suggestion
<main class="flex h-full w-full flex-col gap-5 px-5 pb-2">
```

I agree that the horizontal padding should be same and that the gap to the navigation bar should be consistent, but removing the vertical padding completely position the decision buttons and navigation buttons very close to the bottom margin. What do you think of keeping the bottom padding?

File: src/routes/project/[projectId]/dashboard/+page.svelte [hunk 3]
```diff
@@ -22,8 +22,8 @@
     {/await}
 </svelte:head>
 <ProjectNavigationBar defaultTabValue="dashboard" {loadingProject} {projectId} {user} />
-<main class="mb-10 flex h-full w-full flex-row gap-x-5 overflow-hidden">
-    <section class="h-full w-full py-5">
+<main class="mb-10 flex h-full w-full flex-row gap-x-5 overflow-hidden px-5">
```
Comment (Merseleo) [inline src/routes/project/[projectId]/dashboard/+page.svelte]:
```suggestion
<main class="mb-10 flex h-full w-full flex-row gap-x-15 overflow-hidden px-5">
```

**Review by Merseleo — CHANGES_REQUESTED** [review]
Not only fixed the one ‘problem’, but also corrected the "jumping" of headers in several pages - very attentive, good. 
But there's one thing you could perhaps do at the same time: In the settings, the menu on the left is also very indented, what do you think? Or should we leave it as it is for now or discuss it later?

PS: dont forget to rebase after the changes and re-review please if you do not apply the suggestions.

**Comment by Slartibartfass2** [comment]
@mowi12 we keep this open until #310 is closed so that we see the effect.

File: src/routes/+page.svelte (hunk 1 above)
Comment (mowi12) [reply src/routes/+page.svelte:19]: This is a good idea, but in my opinion 15 is too much. I think 10 would be a better fit.

```suggestion
<main class="mb-10 flex h-full w-full flex-row gap-x-10 overflow-hidden px-5">
```

Comment (mowi12) [reply src/routes/+page.svelte]: Yes, this is a good idea! But I think 15 is a bit much. Please take a look at the new changes, there i used 10 instead. I also added another gap in another file which we missed.

Comment (Merseleo) [reply src/routes/+page.svelte]: I agree, 10 is better.

**Review by Merseleo — DISMISSED** [review]

**Comment by Slartibartfass2** [comment]
Let's not wait for the visual regression tests, I expect that they will still take some time.

**Comment by Merseleo** [comment]
@mowi12 do you want to rebase before I review it again? Otherwise I will review it tomorrow.

File: src/lib/components/composites/list/NamedList.svelte [hunk 4]
```diff
@@ -71,7 +71,9 @@ This can be e.g. a search bar.
 -->
 <div class="flex h-full w-full flex-col gap-y-5 overflow-hidden">
     {#await items}
-        <h2>{listName}</h2>
+        {#if listName}
```
Comment (Merseleo) [inline src/lib/components/composites/list/NamedList.svelte:74]: Why do you check for the `listname`? This should be always true, as you set a default for `listname`?

File: src/routes/project/[projectId]/dashboard/+page.svelte [hunk 5]
```diff
@@ -22,8 +22,8 @@
     {/await}
 </svelte:head>
 <ProjectNavigationBar defaultTabValue="dashboard" {loadingProject} {projectId} {user} />
-<main class="mb-10 flex h-full w-full flex-row gap-x-5 overflow-hidden">
-    <section class="h-full w-full py-5">
+<main class="mb-10 flex h-full w-full flex-row gap-x-10 overflow-hidden px-5">
```
Comment (Merseleo) [inline src/routes/project/[projectId]/dashboard/+page.svelte:25]: Why only `gap-x-10` and not `gap-10`?

Comment (Merseleo) [reply src/routes/project/[projectId]/dashboard/+page.svelte:25]: Same for reading list ...

**Review by Merseleo — CHANGES_REQUESTED** [review]
I only have some questions, but maybe we already discussed this, this PR is already open for too long ^^.

File: src/lib/components/composites/list/NamedList.svelte (hunk 4 above)
Comment (mowi12) [reply src/lib/components/composites/list/NamedList.svelte:74]: This is true, but this also checks if the `listName` is not empty. If it is (e.g. on the reading list page), there is an extra gap between the not existing title and the search bar.
In my opinion, the gap should only exists between component that are visible.

File: src/routes/project/[projectId]/dashboard/+page.svelte (hunk 5 above)
Comment (mowi12) [reply src/routes/project/[projectId]/dashboard/+page.svelte:25]: I actually did only updated the values from `5` to `10`. The `x` was already there. I just tested it, and noticed no difference, which makes sense.
If you want, we can remove the `x` part.

Comment (Merseleo) [reply src/routes/project/[projectId]/dashboard/+page.svelte:25]: No, if it was `gap-x-5` before, I think we've given it some thought.

File: src/lib/components/composites/list/NamedList.svelte (hunk 4 above)
Comment (Merseleo) [reply src/lib/components/composites/list/NamedList.svelte:74]: Ah ok, I did not consider this extra gap, this makes sense.

**Review by Merseleo — APPROVED** [review]
