### PR TITLE
Fix misleading hint shown when no search results could be found

### LINKED ISSUE #374: [Bug]: Misleading hint shown when no search results could be found
### Is there an existing issue for this?

- [x] I have searched the existing issues

### To which use case does your bug report relate?

_No response_

### What happened?

When you search through a list using the custom search component and no results could be found, then the normal `emptyHint` is shown. Actually this hint should only be used if initially the list is empty and not if it is empty after searching or filtering.

### Steps to reproduce

1. Go to the reading list page 
2. Search for an paper that does not exist on the reading list

### What did you expect?

I would expect a more precise hint, e. g. "No search results" or "No results found".

### Anything else?

Image

### PR DESCRIPTION
**Pull request by Merseleo**
Closes #374

## What I have made

- I changed the hint displayed when no search results could be found
  - on the reading list page
  - on the project papers overview page
  - in the lists of the references and citations on the paper view page

## Checklist

Either tick or cross out the items that do not apply (using \~\~example text\~\~) and give a reason why the item does not apply.

- [x] I have updated the documentation accordingly and commented my code
- [x] I have adapted tests that prove my fix is effective or that my feature works
  - ~~[ ] unit tests~~
  - ~~[ ] integration tests~~
  - [x] end-to-end tests
- [x] (for reviewer) I have checked the implementation against the requirements

### CODE REVIEW

File: src/lib/components/composites/paper-components/paper-view/cards/ReferencesAndCitationsCardContent.svelte [hunk 1]
```diff
@@ -44,7 +52,9 @@ Usage:
 <section class="flex h-full flex-col gap-5">
     <div class="flex h-full flex-[1_1_0] overflow-hidden">
         <NamedList
-            emptyHint="No references found."
+            emptyHint={noSearchResultsForBackwardReferencedPapers
+                ? "No references match your search."
+                : "No references found."}
```
Comment (mowi12) [inline src/lib/components/composites/paper-components/paper-view/cards/ReferencesAndCitationsCardContent.svelte]: 'No references match your search' and 'No references found' both sound like the search yielded no result. I think 'No references found' should be something like 'No references exist'. It should be more clear that there simply are no references, not that they couldn't have been found.

'No references exist' is not perfect, maybe you can come up with something better!

File: src/lib/components/composites/paper-components/paper-view/cards/ReferencesAndCitationsCardContent.svelte [hunk 2]
```diff
@@ -65,7 +75,9 @@ Usage:
     </div>
     <div class="flex h-full flex-[1_1_0] overflow-hidden">
         <NamedList
-            emptyHint="No citations found."
+            emptyHint={noSearchResultsForForwardReferencedPapers
+                ? "No citations match your search."
+                : "No citations found."}
```
Comment (mowi12) [inline src/lib/components/composites/paper-components/paper-view/cards/ReferencesAndCitationsCardContent.svelte]: Same here.

**Review by mowi12 — CHANGES_REQUESTED** [review]
I like your changes, well done! There is only one sentence, where I don't like the exact wording. Maybe you don't see it that way, so please let me know what you think.

And regarding the wiki linting, I don't understand the error. Locally, I cannot reproduce the error. The file isn't even that long in that specific line.

File: src/lib/components/composites/paper-components/paper-view/cards/ReferencesAndCitationsCardContent.svelte (hunk 1 above)
Comment (Merseleo) [reply src/lib/components/composites/paper-components/paper-view/cards/ReferencesAndCitationsCardContent.svelte]: You are right, it sounds quite similar. But imo 'No references exist' is really good, as this actually the case.

**Review by Merseleo — COMMENTED** [review]
Thank you for your feedback and suggestions! What do you think of my adaption of your suggestion?

File: src/lib/components/composites/paper-components/paper-view/cards/ReferencesAndCitationsCardContent.svelte (hunk 1 above)
Comment (mowi12) [reply src/lib/components/composites/paper-components/paper-view/cards/ReferencesAndCitationsCardContent.svelte]: I guess you're right. I like the phrasing you chose!

**Review by mowi12 — APPROVED** [review]
Perfect, nicely done!
