### PR TITLE
fix: reload page data after navigation

### LINKED ISSUE #217: [Bug]: No reload of page data after navigation
### Is there an existing issue for this?

- [x] I have searched the existing issues

### To which use case does your bug report relate?

#42

### What happened?

Wenn the user clicks (or double clicks) on a paper in the references / citations list and navigates to this paper page, the navigation is successful (can be seen in the updated URL), but the page is not loaded again and the loaded page data don't update, so the wrong title, authors etc. are shown.

### Steps to reproduce

1. Go to a paper page (e.g. /paper/0)
2. Click on one reference from the "References" list
3. Check the URL updated

### What did you expect?

The new paper page should display the information from the new paper and not from the old paper.

### Anything else?

Image

### PR DESCRIPTION
**Pull request by domienderle**
Closes #217 

## What I have made

I have added derived functions in the ```PaperView.svelte``` and ```paper/[paperId]/+page.svelte``` to translate the updates of the paper if the url is changed.

## Checklist

Either tick or cross out the items that do not apply (using \~\~example text\~\~) and give a reason why the item does not apply.

- ~~[ ] I have updated the documentation accordingly and commented my code~~ not necessary, because I only inserted the ```$derived``` rune 
- [x] I have added tests that prove my fix is effective or that my feature works
  - ~~[ ] unit tests~~ already existed
  - ~~[ ] integration tests~~ already existed
  - ~~[ ] end-to-end tests~~ already existed
- [x] (for reviewer) I have checked the implementation against the requirements

### CODE REVIEW

**Review by domienderle — COMMENTED** [review]
Can be reviewed. The failing pipeline originates from the flaky tests.

**Review by mowi12 — CHANGES_REQUESTED** [review]
Your changes look very good. I mean, there is not much to look at, which is good!
But I have two requests.

The first thing that came to mind is, that the page always quickly shows the skeletons while reloading. This is kinda annoying.
The problem is, that we actually redirect to a new page (i think), since we are actually changing the URL, although we are still in the same svelte file.

Try having a look at the code in branch feat/100. If I remove a paper from the reading list, there is no reload, and no skeletons are shown. This is because I only update the UI after the new papers are loaded.

Felix did the same here (he sent me those some time ago):

Da wird das neu geladen:
https://github.com/SE-UUlm/snowballr-frontend/blob/9130e0e12aa74e4e2279f2c4b4242fcd784bc51c/src/routes/project/%5BprojectId%5D/settings/members/%2Bpage.svelte#L30
Da ruf ich den Callback auf:
https://github.com/SE-UUlm/snowballr-frontend/blob/9130e0e12aa74e4e2279f2c4b4242fcd784bc51c/src/lib/components/composites/settings/project-settings/members/InviteUsersDialog.svelte#L57


Second, you checked the checkmark, that the e2e test already exists. But I think, there is no e2e test for clicking on the references of a paper.
Add or create a new use case for clicking on things in the paper view, which in your case, only needs to test the switching of the paper view.

**Review by domienderle — COMMENTED** [review]
The first change is not possible. The entries in the referenced papers are of ```PaperListEntry```. This entries have to implement a ```goto()``` method, because in other lists where ```PaperListEntry``` elemts are used it is required to change the page to the requested ```URL```. But with #362 the time of the loading should be as minimal as possible, because then the ressources are preloaded (as long as single and double click on the referenced paper entries are the same).

**Review by domienderle — COMMENTED** [review]
You are right. I didn't really look into the e2e tests. Now I created a test, that checks if the navigation works properly, by clicking on a referenced paper (which should cover all of this fix issue).

File: tests/e2e/pom/paper-view-model.ts [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+export class DevPaperViewPage {
+    readonly page: Page;
+    readonly allListEntries: Locator;
+    readonly referenceListEntry0: Locator;
+
+    constructor(page: Page) {
+        this.page = page;
+        this.allListEntries = page.getByRole("listitem");
+        this.referenceListEntry0 = page
```
Comment (mowi12) [inline tests/e2e/pom/paper-view-model.ts]: I think you wanted to use the `allListEntries` var, correct?

```suggestion
        this.referenceListEntry0 = allListEntries
```

File: tests/e2e/pom/paper-view-model.ts [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+            .getByRole("button", {
+                name: /Paper 0 to be referenced/,
+            })
+            .nth(0);
```
Comment (mowi12) [inline tests/e2e/pom/paper-view-model.ts]: Imo, `first()` looks a bit cleaner if you only want the first item. What do you think?

File: tests/e2e/pom/paper-view-model.ts [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+    readonly page: Page;
+    readonly allListEntries: Locator;
+    readonly referenceListEntry0: Locator;
+
+    constructor(page: Page) {
+        this.page = page;
+        this.allListEntries = page.getByRole("listitem");
+        this.referenceListEntry0 = page
+            .getByRole("button", {
+                name: /Paper 0 to be referenced/,
```
Comment (mowi12) [inline tests/e2e/pom/paper-view-model.ts]: You can actually just use a string instead of the regex, since you do not use any regex parts.

```suggestion
                name: "Paper 0 to be referenced",
```

If you had used `name: "Paper 0 to be referenced", exact: true`, then this would make a difference, but without it, it does not need to be exact.

File: tests/e2e/paper-navigation.test.ts [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+        papers.forEach((paper) => paperIds.push(paper.id));
+    });
+
+    test("When clicking on a referenced paper in the paper view (no project paper) the paper view of the referenced paper is shown", async ({
+        page,
+        paperViewPage,
+    }) => {
+        await paperViewPage.openPaperView(paperIds[1]);
+        await paperViewPage.navigateToReferencedPaper();
+        await expect(page.getByText("Paper 0 to be referenced").nth(0)).toBeVisible();
```
Comment (mowi12) [inline tests/e2e/paper-navigation.test.ts]: Same here, I think `first()` is a bit cleaner if only the first element is relevant.

```suggestion
        await expect(page.getByText("Paper 0 to be referenced").first()).toBeVisible();
```

**Review by mowi12 — CHANGES_REQUESTED** [review]
Nice, now everything looks good. I only have some minor suggestions for you to take a look at. But then we are done!

File: tests/e2e/pom/paper-view-model.ts (hunk 2 above)
Comment (domienderle) [reply tests/e2e/pom/paper-view-model.ts]: I guess, that is true.

File: tests/e2e/pom/paper-view-model.ts (hunk 3 above)
Comment (domienderle) [reply tests/e2e/pom/paper-view-model.ts]: Yes. That is just a remnant of previous tries.

**Review by mowi12 — APPROVED** [review]
Now everything looks good!

One small thing. In the future let the reviewer resolve the conversations, he is the one who has to decide if your changes are good, or not. In this case I already gave you suggestions, but you know : )
